server:
  port: 8090

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/foodie_shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: 804232452
  redis:
    database: 1
    host: 140.238.64.24
    port: 6379
    password: 804232452

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl